server:
  port: 8888
  servlet:
    context-path: /e-wallet

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbjunit5?createDatabaseIfNotExist=true&autoReconnect=true&showSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.hcl.wallet.controller: DEBUG
    com.hcl.wallet.security: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
